---
title: " select"
author:
- familyname: Shi
  othernames: Jingyi
  address: Monash University
  email: jshi0067@student.monash.edu
  correspondingauthor: true
  qualifications:  32267886
- familyname: Sun
  othernames: Miao
  address: Monash University
  email: msun0008@student.monash.edu
  correspondingauthor: true
  qualifications: 28380584
- familyname: Ou
  othernames: Jingwen
  address: Monash University
  email: jouu0006@student.monash.edu
  correspondingauthor: true
  qualifications:  32269633
- familyname: Qin
  othernames: Yu
  address: Monash University
  email: yqin0016@student.monash.edu
  correspondingauthor: true
  qualifications:  32606745
department: Faculty of Business and Statistic
organization: Monash University ETC5513 Group Really3Q
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    citation_package: biblatex
    toc: false
---
```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(knitr)
library(plotly)
```

## Introduction

## Main body

### Australia and New zealand

```{r read_data, results='hide'}
annual_number_of_deaths_by_cause <- read_csv("Data/annual-number-of-deaths-by-cause.csv", 
    col_types = cols(`Number of executions` = col_double()))
life_expectancy <- read_csv("Data/life-expectancy.csv")
share_with_depression <- read_csv("Data/share-with-depression.csv")
```

1.List all kinds of death causes
```{r deathcauses}
world_data <-annual_number_of_deaths_by_cause %>% 
  filter(!is.na(Code),
         Year %in% c(1990:2018)) %>%
  pivot_longer(cols =  -c(1:3), 
               names_to = "Death_cause", 
               values_to = "Count") %>% 
  group_by(Year,Death_cause) %>% 
  summarise(Death_amount=sum(Count, na.rm = TRUE))

world_data %>% filter(Year==1990) %>% 
  pull(Death_cause) %>% 
  kable(caption = "The caueses of death")

```

For this table\@ref(tab:deathcauses),

2.World data
```{r worldtable}
world_data %>% 
  filter(Year==2018) %>% 
  arrange(desc(Death_amount)) %>% 
  head() %>% 
  kable(caption = "The world' top six causes of death in 2018")
```

```{r worldplot,fig.cap ="Number of deaths by cause, World, 1990 to 2019"}
ggplot(world_data,
       mapping = aes(x=Year,
                     y=Death_amount,
                     color=Death_cause))+
  geom_line()+
  theme_bw()
```
\@ref(fig:worldplot)

3.Australia and New Zealand data

(1).Select death due to disease factors
```{r diseaseplot,fig.cap="Number of deaths by disease causes, 1990 to 2018"}
disease_data <- annual_number_of_deaths_by_cause %>% 
  select(1,3,5,6,7,8,9,12,13,14,15,16,17,18,22,24,26,27,32,33,34,36) %>% 
  filter(Country %in% c("Australia","Switzerland"),
         Year %in% c(1990:2018)) %>% 
  pivot_longer(cols =  -c(1:3), 
               names_to = "Death_cause", 
               values_to = "Count")

AZ_life_expectancy <- life_expectancy %>% filter(
  Entity %in% c("Australia","Switzerland"),
  Year %in% c(1990:2018)
) %>% 
  rename("Country" = "Entity",
         "Life_expectancy" = "Life expectancy") %>% 
  select(-Code)

DL_data <- disease_data %>% 
  left_join(AZ_life_expectancy,by=c("Country","Year"))

ggplot(DL_data,
       mapping = aes(x=Year,
                     y=Count,
                     color=Death_cause))+
  geom_line()+
  geom_line(aes(y=Life_expectancy*500),
            color="#1CDC4B",
            size=1)+
  geom_point(aes(y=Life_expectancy*500),
             color="#12F09E",
             size=1)+
    scale_y_continuous(name = "Number of deaths by disease causes",
    sec.axis = sec_axis(trans =~./500,
                        name = "Life expectancy"))+
    facet_wrap(~Country,
             scales = "free_y")+
  theme_bw()

```

(2).select death due to other factors
```{r otherplot,fig.cap="Number of deaths by other causes, 1990 to 2018"}
other_data <- annual_number_of_deaths_by_cause %>% 
  select(1,3,4,10,11,19,20,21,23,25,28,29,30,31,35) %>% 
  filter(Country %in% c("Australia","Switzerland"),
         Year %in% c(1990:2018)) %>% 
  pivot_longer(cols =  -c(1:3), 
               names_to = "Death_cause", 
               values_to = "Count")


AZ_share_with_depression <-share_with_depression  %>% filter(
  Entity %in% c("Australia","Switzerland"),
  Year %in% c(1990:2018)
) %>% 
  rename("Country" = "Entity",
         "Depressive_disorders" = "Depressive disorders") %>% 
  select(-Code)

DD_data <- other_data %>% 
  left_join(AZ_share_with_depression,by=c("Country","Year"))




 ggplot(DD_data,
       mapping = aes(x=Year,
                     y=Count,
                     color=Death_cause))+
  geom_line()+  
  geom_line(aes(y=Depressive_disorders*300),
            color="#2399F5",
            size=1)+
  geom_point(aes(y=Depressive_disorders*300),
             color="#99C3E5",
             size=1)+
    scale_y_continuous(name = "Number of deaths by other causes",
    sec.axis = sec_axis(trans =~./300,
                        name = "Depressive disorders %"))+
  
    facet_wrap(~Country,
             scales = "free_y")

```




@ggplot, @tidyverse,@readr






## Colusion